/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLHSUI;

import QLHSmodel.ConnectSQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import object.hocSinh_if;

/**
 *
 * @author vao12
 */
public class hocSinh_xoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form hocSinh_xoa
     */
    public hocSinh_xoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmahs = new javax.swing.JTextField();
        btluu = new javax.swing.JButton();
        nthuy = new javax.swing.JButton();
        btreset = new javax.swing.JButton();
        btchon = new javax.swing.JButton();

        setTitle("Xóa Học Sinh");

        jLabel1.setText("Mã học sinh");

        btluu.setText("Lưu");
        btluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btluuActionPerformed(evt);
            }
        });

        nthuy.setText("Hủy");
        nthuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nthuyActionPerformed(evt);
            }
        });

        btreset.setText("reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        btchon.setText("Chọn HS");
        btchon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btchonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btluu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btchon)
                        .addGap(12, 12, 12)
                        .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nthuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmahs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btluu)
                    .addComponent(nthuy)
                    .addComponent(btreset)
                    .addComponent(btchon))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btluuActionPerformed
        hocSinh_if hs=new hocSinh_if();
        if (txtmahs.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Điền mã học sinh cần xóa");
        } else {
            boolean check = true;
            ConnectSQL conn = new ConnectSQL();
            ResultSet rs1 = conn.getdata("select maHS,maLop from hocSinh_infor");
            try {
                while (rs1.next()) {
                    if (!rs1.getString(1).equals(txtmahs.getText())) {
                        check = check && false;
                    } else {
                        check = check || true;
                        hs.setMahs(rs1.getString(1));
                        hs.setDiachi("p");
                        hs.setDantoc("d");
                        hs.setGioitinh("n");
                        hs.setHoDem("s");
                        hs.setLienkhoa("d");
                        hs.setMaLop(rs1.getString("maLop"));
                        hs.setNgaySinh("s");
                        hs.setTenhs("h");
                        break;
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(pnhocsinh.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (check == false) {
                JOptionPane.showMessageDialog(this, "Không có học sinh này ! Điền đúng mã học sinh");
            } else {
                int output=JOptionPane.showConfirmDialog(this,"Bạn xác nhận muốn xóa học sinh này","Xóa học sinh ?", JOptionPane.YES_NO_OPTION);
                if(output==JOptionPane.YES_OPTION)
                {
                conn.xoaHocSinh(hs);
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                }
                else{}
            }
        }
    }//GEN-LAST:event_btluuActionPerformed

    private void nthuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nthuyActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_nthuyActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        txtmahs.setText("");
    }//GEN-LAST:event_btresetActionPerformed

    private void btchonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btchonActionPerformed
        if (pnhocsinh.hsif.getMahs().equals("0")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một học sinh trong bảng bên cạnh");
        }
        else
        {
        txtmahs.setText(pnhocsinh.hsif.getMahs());
        }
    }//GEN-LAST:event_btchonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btchon;
    private javax.swing.JButton btluu;
    private javax.swing.JButton btreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nthuy;
    private javax.swing.JTextField txtmahs;
    // End of variables declaration//GEN-END:variables
}
